language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
notifications:
  email:
    on_success: never
    on_failure: always

before_script:
- rustup toolchain install nightly
- rustup component add clippy
- rustup component add rustfmt
script:
- cargo clean
- cargo build
- cargo clippy -- -D warnings
- cargo fmt --all -- --check
- RUST_BACKTRACE=1 cargo test
